spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=update

# Guild/Raid group config
guild.timezone=America/New_York
guild.raid-start-time=21
guild.raid-days=TUESDAY,WEDNESDAY,THURSDAY
guild.reset-day=TUESDAY
#Currently set to the test channel
guild.notification-schedule=0 0 12 * * TUE,WED,THU
guild.officer-channel-id=1525606436066033815